[package]
name = "frila"
version = "0.1.0"
edition = "2021"

[dependencies]
pushy = "= 0.1.0"
mysql = { path = "./rust-mysql-simple" }
argv = "0.1.5"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
